### ISSUE TITLE
Unable to identify discord name

### ISSUE THREAD

**Issue by SmoothBrainApe** [kevinthedang/discord-ollama#110]
I am not sure if this is a bug or a feature that has not yet been implemented, but when I chat with the bot, it does not know me. It is unable to read my username in discord.

![testing](https://github.com/user-attachments/assets/7399033e-ccb9-48e8-9ff4-adcf0f13ebb9)

This is going to be an issue if multiple people in channel start to have a conversation with the same bot. Just letting you know in case you are not aware @kevinthedang

**Comment by kevinthedang** [comment]
Nope! This is not an issue actually as different users will have different chat histories with the bot! 

Say, for example, you and I talk to this chat bot. Two different files are created to track our conversations in the channel we talk in. You can find your chat history in the data folder.

This however is an issue with creating a public thread and having multiple people. This however is already has been noticed and will be worked on eventually.

If you want, we can have the application have the users name and I'd from the Discord client.

Thanks for the heads up!

**Comment by kevinthedang** [comment]
@JT2M0L3Y 

Your discretion of whether or not to close this. I believe we have an issue about removing the **channel-toggle** Slash Command which should be solving the multiple users in a public thread.

**Comment by JT2M0L3Y** [comment]
@kevinthedang @SmoothBrainApe 

Thankfully, if this is something we find could be useful in the future this issue can be reopened.
