### ISSUE TITLE
Image recognition from messages with attachments with Llava

### ISSUE THREAD

**Issue by nololler** [kevinthedang/discord-ollama#116]
## Issue
The bot which uses llava:7b as the model does not "see" the images attached to a message. 

## Solution
* Provide steps or ideals to how to implement or investigate this new feature.
I don't know how programming works but the bot could check if there's an attachment when a message is sent, and if there is, send the image along with the original message to llava. Either by sending the media link of the image or downloading the image into a temp folder and sending the image's location to llava, the user can have the option to enable auto deletion of cached images that aren't needed.

## References
* Provide additional context and external references here
![image](https://github.com/user-attachments/assets/91d8d473-9a3e-4eed-a1e4-2f3055898b1f)
![image](https://github.com/user-attachments/assets/b82e6b70-dc78-40dd-9dde-92c8d8fe2ba5)

**Comment by kevinthedang** [comment]
Yup this sounds like something useful. Had thoughts on it before and tested this. Had the same results as you.

We can definitely get some work on this.

## Sample Implementation based on saving an image file
```ts
import ollama from 'ollama'

const res = await ollama.chat({
	model: 'llava',
	messages: [{
		role: 'user',
		content: 'Describe this image:'
		images: ['./art.jpg']
	}]
})
```

## Image Recovery from Discord.js
```ts
client.on('message', async message => {
    let messageAttachment = message.attachments.size > 0 ? message.attachments.array()[0].url : null
    let embed = new Discord.MessageEmbed();
        embed.setAuthor(message.author.tag, message.author.avatarURL())
        if (messageAttachment) embed.setImage(messageAttachment)
        embed.setColor(14680086)
        await message.channel.send(embed)
        message.delete()
})
```

cc: @JT2M0L3Y

**Comment by kevinthedang** [comment]
Works for now, issues with message history as it seems to prioritize the first image shown. Hallucinations are likely to happen. Trying to figure out a workaround.

![image](https://github.com/user-attachments/assets/8902e238-6c6a-434d-bfc4-dcb249221093)

**Comment by nololler** [comment]
Can't wait for this feature :D
