### ISSUE TITLE
Ollama Chat Threads

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#13]
## Steps to Reproduce
* Run the bot on 1 machine (server or local machine)
* Allow 1 person to run a query from the bot
* Then another **different** person queries the bot
* The result should be similar as below

![image](https://github.com/kevinthedang/discord-ollama/assets/77701718/89ac9abc-aa39-409a-9fdd-65800a2523d8)

## Ideas
* It would be nice to reduce the clutter on a channel by allowing the bot to create threads and chat individually with a user
  * The permissions of the thread should only be writable to the bot and the conversation with another user.
  * It should be fine for other users to view the thread, but not create queries (chat)
  * Refer below as an example from #12 called `threadCreate.ts`. Maybe the same way but instead it is on a new query.
    * Shifts message to thread and creates an ephemeral message (somehow)
    * We want to store the `threadId` and make sure that it is a parent of this thread is the one in the environment.

![image](https://github.com/kevinthedang/discord-ollama/assets/77701718/98a548d7-e802-431e-af0f-4331cfbfc08a)

**Comment by kevinthedang** [comment]
Just found this out while testing out the slash command:
* Threads have their own channels (so kind of like a child process in a OS)
* There is no `threadMessageCreate` so we just have to use `messageCreate` to handle valid chat instances
  * For example, let's say we have 2 chat threads with ids 123 and 124. The bot should only validate `messageCreate` somehow within those channels. 
  * When `threadCreate` is called, we want to add it to the instance of valid channels to run Ollama.
  * When `threadDelete` is called, we want to remove it from the instance of valid channels to run Ollama in.
  
The [Client Class](https://discord.js.org/docs/packages/discord.js/14.14.1/Client:Class) found in the discord.js docs lists all of their interactions and brief descriptions of how they work.

![image](https://github.com/kevinthedang/discord-ollama/assets/77701718/9990ffc4-7288-4c25-a7a7-a14a52ad7228)

**Comment by kevinthedang** [comment]
Since we are dealing with channels that are "valid", meaning they are still up and being used, we need a way to store them:

I thought about:
1. Storing via json file, editing and removing from it. We can already do that like with the config so it's possible. What is also cool is that we can create configs for different users and put it in their threads/channels/servers so different for each type. What differs between them? Not sure! We'll figure that out later.
2. Some kind of external service, but it would be nice to not depend on other services and only depend on the `discord.js` package development to reduce dependencies.

**Comment by kevinthedang** [comment]
Just had a thought:
* If a user ran the `/thread` command again, it would generate another chat thread. Should we allow this or prevent multiple chats threads with the same user? @JT2M0L3Y

**Comment by kevinthedang** [comment]
Another thing is when a thread is created these appear:

![image](https://github.com/kevinthedang/discord-ollama/assets/77701718/63bf0ef3-bfe0-46f6-93a7-48146f4a6fe4)

Should we clean this up using the bot or should we leave them there. @JT2M0L3Y

**Comment by JT2M0L3Y** [comment]
@kevinthedang
I think users should be allowed multiple threads.
We should clean up the remnant thread messages in the main channel stream.

**Comment by kevinthedang** [comment]
@JT2M0L3Y New Idea for this...

We allow threads to be created everywhere, but the bot can no longer talk in channels.

The only exception for this is in #43 as the bot would talk in a regular public channel.

**Comment by JT2M0L3Y** [comment]
Definitely.

**Comment by kevinthedang** [comment]
## Extra Stuff
* Introducing Redis would be nice... here are some resource @JT2M0L3Y 
  * [Redis for Node.js](https://redis.io/docs/latest/develop/connect/clients/nodejs/)
  * [Redis](https://redis.io/)
  * Talks about how [Redis Improves Performance](https://www.youtube.com/watch?v=vXycKhl0hu4)
  * [YouTube Playlist on Redis](https://www.youtube.com/playlist?list=PL4cUxeGkcC9h3V2eqhi8rRdIDJshP-b4P)

**Comment by kevinthedang** [comment]
Thoughts:
* Going to move the redis stuff off this issue and keep it on #57. It will not be required for this issue to close.
* Likely #59 will be completed along with this issue.

@JT2M0L3Y
