### ISSUE TITLE
Ollama Network Connection - Pull/Switch Model

### ISSUE THREAD

**Issue by JT2M0L3Y** [kevinthedang/discord-ollama#139]
When attempting to execute the new pull- and switch-model commands, I am having issues connecting to the ollama container to finish the fetch.

**To Reproduce**
1. Start the discord and ollama containers.
2. Set config settings in the discord container.
3. Attempt to run the pull-model command.
5. See that the discord container exits with an error.

**Expected behavior**
This has been proven to work correctly in the environment @kevinthedang has created. It should pull models from Ollama's bank into the container such that they can be selected from within the client and used.

**Screenshots**
![image](https://github.com/user-attachments/assets/60a66905-80fc-4e65-a452-649d4796fd45)

**Desktop (please complete the following information):**
 - OS: Ubuntu (WSL2)
 - Version: 22.04.5 LTS (jammy)

**Comment by kevinthedang** [comment]
How did you start the container? Naturally it does not matter but just curious for reproducing. Sometimes Compose is weird.

@JT2M0L3Y 

```json
"start": "docker compose build --no-cache && docker compose up -d"
```

or

```json
"docker:start": "docker network prune -f && npm run docker:network && npm run docker:build && npm run docker:client && npm run docker:ollama"
```

**Comment by JT2M0L3Y** [comment]
I did not use compose. I created each container (and network) separately.

**Comment by JT2M0L3Y** [comment]
Used the `start` npm script tonight to spin up a new set of containers, worked like a charm on v0.8.0.

Wonder if it had something to do with message embedding...
Other than human error, this looks to be the only major change to the codebase since the bug arose.
