### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#14]
## Issue
* There are no unit tests that exist for this project to ensure that all versions are working as intended.
* Having code coverage being as high as possible is good practice :)

## Solution
* Work on creating unit tests for certain events
  * Logging in (`ready.ts`)
  * `messageCreate.ts`
  * `interactionCreate.ts`
  * etc.
* Should look into testing framworks that match typescript and work well with discord bots
* Should display that tests are passing in `README.md` and the code coverage of the codebase

**Comment by kevinthedang** [comment]
Looked into creating tests using `vitest`. It does not seem to be useful for now. Will probably look into this later. Typically we will also be testing features before releasing them. Only possibly problem is package deprecation.

**Comment by kevinthedang** [comment]
## Update
Gonna reopen this so we really can have some kind of code coverage for the project to ensure certain parts are working as intended.

* We will try to use [jest](https://jestjs.io/docs/getting-started#using-typescript) with TypeScript
* We also need to make sure we follow this for [ECMAScript](https://jestjs.io/docs/ecmascript-modules)
* [Mock Testing](https://jestjs.io/docs/mock-functions) will be important
* Future thing to consider ---> [Redis Testing](https://stackoverflow.com/questions/60541602/how-to-mock-node-redis-using-jest)


Currently we should add these testing dependencies
```css
npm install --save-dev jest @types/jest ts-jest
```

**Comment by JT2M0L3Y** [comment]
File Structure Options:  
* Should the source code for this project be bundled properly for delivery or deployment some where, it would make sense to separate the `tests` and `src` directories.  
* Since we simply listen for specific events, messages, and commands happening in discord (but, don't deploy anything to discord), it is suitable to place any test files within the `src` directory so they are as close as possible to code that will be tested.

**Comment by JT2M0L3Y** [comment]
> Looked into creating tests using `vitest`. It does not seem to be useful for now. Will probably look into this later. Typically we will also be testing features before releasing them. Only possibly problem is package deprecation.

Upon further research, it would take more overhead than it is worth to use vitest since we are not using Vite within this project.

**Comment by JT2M0L3Y** [comment]
Also, let's plan to test the TS source code before it is compiled over to JS. This ensures we are testing the code itself.

**Comment by JT2M0L3Y** [comment]
> ## Update
> Gonna reopen this so we really can have some kind of code coverage for the project to ensure certain parts are working as intended.
> 
> * We will try to use [jest](https://jestjs.io/docs/getting-started#using-typescript) with TypeScript
> * We also need to make sure we follow this for [ECMAScript](https://jestjs.io/docs/ecmascript-modules)
> * [Mock Testing](https://jestjs.io/docs/mock-functions) will be important
> * Future thing to consider ---> [Redis Testing](https://stackoverflow.com/questions/60541602/how-to-mock-node-redis-using-jest)
> 
> Currently we should add these testing dependencies
> 
> ```css
> npm install --save-dev jest @types/jest ts-jest
> ```

Mocking with DiscordJS is currently in development with this open-source project called [gauntlet](https://github.com/ephemeralrogue/gauntlet)

**Comment by JT2M0L3Y** [comment]
## Update
* Initial unit testing with `vitest` for non-discordjs classes, methods, and features started
* Testing status (as a whole) now has a badge in the `README.md`.
