### ISSUE TITLE
Bug: GitHub Actions Build Environment Failed

### ISSUE THREAD

**Issue by JT2M0L3Y** [kevinthedang/discord-ollama#153]
**Describe the bug**
In the latest push to master (12/30/2024) the container build failed and, though it passed, the local build failed to start the client.

**To Reproduce**
1. Navigate to the actions
2. Click on the failed workflow
3. Click on the 'node-build' and its 'start ... client' task
4. Click on the 'container-build'
5. See error

**Expected behavior**
Both jobs should pass without error (i.e., loading necessary resources and starting the client/containers).

**Screenshots**
![image](https://github.com/user-attachments/assets/4232dd56-cbdb-477a-b2d4-1f72d54670e6)
![image](https://github.com/user-attachments/assets/64089b9a-0264-4d5c-8945-12bdfcfd4959)

**Desktop:**
 - OS: Ubuntu (default-runner)
 - Version 22.04

**Additional context**
I have a few suspicions about what is causing this issue:
* with the node-build, it could be a need to add GitHub secrets to the repo for REDIS_IP and REDIS_PORT
* for the container-build, it could be an issue with the node upgrade from 18 to 22

**Comment by kevinthedang** [comment]
Added the `REDIS_IP` and `REDIS_PORT` secrets and it fixes the container-build job.

**Comment by kevinthedang** [comment]
This also fixes the node-build job. Closing this issue.
