### ISSUE TITLE
Ollama WebUI Integration

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#17]
## Feature
Since discord can be a bit stuck up in terms of data rates (it totally makes sense), implementing the webui as a slash command can be helpful, it would still utilize some kind of database to persist the data (or unless `ollama-webui` has something built into it for that).

## Idea
* User runs slash command to open up hyperlink to the running webui.
* WebUI will query the database for conversations that a user has.
  * Maybe implement [Redis](https://redis.io/) with this?

## References
* [ollama-webui](https://github.com/ollama-webui/ollama-webui)
  * [Troubleshooting ollama-webui](https://github.com/ollama-webui/ollama-webui/blob/main/TROUBLESHOOTING.md)
  * Possible Docker command to run to make this work: `docker run -d --network=host -v ollama-webui2:/app/backend/data -e OLLAMA_API_BASE_URL=http://127.0.0.1:11434/api --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main`
* Note: The first person to create an account on the webui is made into the administrator and they can approve more users after that. This will probably be useful to approve of students, and only students, to use the interface.

**Comment by JT2M0L3Y** [comment]
The devs no longer consider the purpose in pursuing this feature.
