### ISSUE TITLE
Creating an LLM Using Ollama & Web Content

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#22]
## Idea
* The purpose of this project is to have a bot utilizing a large language model work on a server. 
* Now, the team wants to create documentation on how to create your own model based on the information on a website (i.e. Information about a University/College)
* Hopefully, we can build a web scrapper to scrap data that can be fed into a `Modelfile` to allow a Model to learn about a topic/area.

## References
* We will be looking to how to create a model both from scratch and by attaching.
  * [Customizing a Prompt](https://github.com/ollama/ollama?tab=readme-ov-file#customize-a-prompt) with ollama
  * [Creating a model](https://github.com/ollama/ollama?tab=readme-ov-file#create-a-model) with ollama
    * A lot to learn here! Or not...?
    * Web scrapping with [Beautiful Soup!](https://beautiful-soup-4.readthedocs.io/en/latest/)
  * Refer below for an example

## Sample Creation
Pulling the model:
```yml
ollama pull llama2
```

Modelfile:
```yml
FROM llama2

# set the temperature to 1 [higher is more creative, lower is more coherent]
PARAMETER temperature 1

# set the system message
SYSTEM """
You are Mario from Super Mario Bros. Answer as Mario, the assistant, only.
"""
```

Testing:
```yml
ollama create mario -f ./Modelfile
ollama run mario
>>> hi
Hello! It's your friend Mario.
```

## Goal
This documentation will likely release on `v1.0.0` and up as that will (should) be the end of this project besides maintaining and updating package versions.

**Comment by JT2M0L3Y** [comment]
This idea can be expressed in a section in the README about extending the project beyond what is planned by the present contributors as this project approaches a year in development.
