### ISSUE TITLE
User Preferences vs Server Preferences

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#36]
## Issue
* The current implementation of "User Preferences" works but applies on a server level, meaning it applies to everyone in that server.

## Solutions
* Create a system for distributing configurations based on someones discord username.
  * The following is an idea of how to store via json
```json
{
  "name": "Discord Ollama Confirgurations",
  "servers": {
    "server1": {
      "toggle-chat": true
    },
    "server2": {
      "toggle-chat": false
    }
  },
  "users": {
    "user1": {
      "options": {
        "message-style": false,
        "modify-capacity": 10
      }
    },
    "user2": {
      "options": {
        "message-style": false,
        "modify-capacity": 20
      }
    },
    "user3": {
      "options": {
        "message-style": false,
        "modify-capacity": 30
      }
    }
  }
}
```
* We would have to separate by servers and users for consistency if the bot was used in different servers. Is that likely? Who knows as it is not really accounted for in our scope as a **Multi-Server Bot**. The Bot is to be hosted by an individual for their purposes only/servers.
  * Idea 2:
```json
{
  "name": "Discord Ollama Confirgurations",
  "servers": {
    "server_name1": {
      "toggle-chat": true,
      "users": {
        "user1": {
          "options": {
            "message-style": false,
            "modify-capacity": 10
          }
        },
        "user2": {
          "options": {
            "message-style": true,
            "modify-capacity": 20
          }
        }
      }
    },
    "server_name2": {
      "toggle-chat": false
      "users": {
        "user3": {
          "options": {
            "message-style": false,
            "modify-capacity": 30
          }
        },
        "user4": {
          "options": {
            "message-style": true,
            "modify-capacity": 40
          }
        }
      }
    }
  },
}
```
* Next idea would be storing in different files in a folder in the containers as `server_name.json` for that servers configurations in a `config/` folder.
  * Then a server will only need to look for their own config files and try to run them.
  * We could also use some more preferences... brainstorming time...

**Comment by JT2M0L3Y** [comment]
One idea here is to use the roles feature to issue roles for certain permissions to each user that may need one or want one. This can be an admin-level slash command.

**Comment by kevinthedang** [comment]
@JT2M0L3Y 

Referring #13 as it should also include this because of the Redis dependency we are likely adding for performance and storage.

**Comment by kevinthedang** [comment]
Thoughts:
* I just want to mention #31 when implementing this as "role-based" commands have been implemented but only for admins.
* For dynamicly understanding server roles, we can have the bot scrape the roles whenever they are edited. How do we do that? Not sure right now, but it's an idea.
* Besides administrators? What is the point of caring about roles? 
* Instead of 1 huge json file, we can have separate json files and look for them. This idea is just following a tree structure for files rather than 1 massive file. Either way works.

@JT2M0L3Y

**Comment by JT2M0L3Y** [comment]
Update:

We could store the entire contents of the aforementioned JSON file as a value in Redis and link it to a "user preferences" key.

**Comment by kevinthedang** [comment]
My Idea for a new approach, have a `configs.json` file and store everything there for now... or we create separate files to support the Redis caching we plan on doing.

My initial thoughts:
```ts
export interface UserConfiguration {
    'message-stream'?: boolean,
    'message-style'?: boolean,
    'modify-capacity': number
}

export interface ServerConfiguration {
    'toggle-chat'?: boolean,
    'channel-toggle'?: boolean
}

/**
 * Parent Configuration interface
 * 
 * @see serverOptions server settings per guild
 * @see userConfigurations user configurations (only for the user for any server)
 */
export interface Configuration {
    readonly name: string
    serverOptions: {
        [guildId: string]: ServerConfiguration
    },
    userConfigurations: {
        [username: string]: UserConfiguration
    }
}
```

The Redis plan would look similar, but instead of 1 file, it's just multiple files for users and servers (or 1 file for servers idk). This allows the bot to be compatible for multiple servers with their own settings and for users having their own settings.

@JT2M0L3Y

**Comment by JT2M0L3Y** [comment]
I only have one concern, about the definition of each configuration. 
- Does `modify-capacity` require a user to set it? (there's a default capacity, if I remember correctly)
- Should setting `toggle-chat` be optional?

**Comment by kevinthedang** [comment]
1. No. It will always default to 5 for performance's sake.
2. I mean we can. If you want?

@JT2M0L3Y

**Comment by kevinthedang** [comment]
For now I will develop them separately:
1. User Preferences file
2. Server Preferences file

If you have any other questions just let me know.

@JT2M0L3Y
