### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#69]
## Issue
* We don't exactly know how much of our codebase is covered to ensure there is no regression in functionality. We have a command that can be found in the `package.json` called `"test:coverage": "vitest run --coverage"`

## Solution
* Implement some kind of visual in the readme on how much the code is covered.
* It would also be nice to investigate how to put the code coverage in the PR (with some quick research it might be tough).
  * This would be useful as if code coverage goes down, we want to implement tests to mitigate or even improve coverage.

## References
* #14 
* #60

**Comment by JT2M0L3Y** [comment]
Something like [CodeCov](https://about.codecov.io/) may be worth checking out for this. However, this looks to be the most promising if this repository's ownership migrates to an organization.

**Comment by kevinthedang** [comment]
In all honesty, are we really going to implement #17? It was an interesting idea, but it seems against the idea of a "Discord Chat Bot" when you just move to a webpage.

Considering a close on #17 because it will become extraneous to this project. What do you think?

@JT2M0L3Y

**Comment by JT2M0L3Y** [comment]
I was thinking the same thing. Plus, it's what everyone else seems to be interested in doing with Ollama.

**Comment by JT2M0L3Y** [comment]
Using this resource: https://github.com/Schneegans/dynamic-badges-action/
Need to add a few repository secrets for this to work...

**Comment by JT2M0L3Y** [comment]
@kevinthedang Please follow these steps to allow the code coverage workflow to work properly:

1. go to https://gist.github.com/ and create a new private gist
2. grab the `gist id` from the link available to clone your new gist:
![image](https://github.com/user-attachments/assets/07dc09ad-5462-459d-9de1-dee9b24f08ae)
3. generate a secret for this repo named `GIST_TOKEN` and give it only `gist` permissions
4. provide me with both the `GIST_ID` and `GIST_TOKEN` 
    * I'm looking into treating the `GIST_ID` as a secret as well, but I'm 100% on this yet

**Comment by kevinthedang** [comment]
Where do you want me to run this? (what branch?)

cc: @JT2M0L3Y

**Comment by JT2M0L3Y** [comment]
@kevinthedang Use the `bug/tech-debt` branch please.
