### ISSUE TITLE
Ollama History Performance Issues

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#7]
## Issue
* Response times are linear in accordance with when a message has been sent, this will be a problem as if (for example) 5 people want to query the boy at the same time, it runs the queries linearly which will be inconvenient.

## Notes
* There probably won't be that many users using it at the same time so there will be a static capacity on threads
* Future feature would be to dynamically check cores on a system and figure out how many threads to allow Ollama to run on and set in the settings (Util feature).

**Comment by JT2M0L3Y** [comment]
Conversations can be piped into individual threads via a slash command added by @kevinthedang.

**Comment by kevinthedang** [comment]
Sorry I chose a poor name for this. This should be about how Ollama performs as more messages appear.

## Update
* Figure out some way to increase performance of models with message history
* Redis can be something we can use for history...

**Comment by kevinthedang** [comment]
## Update
* To increase performance as of now, we can use a docker image.
* Refer to the following:
  * [Nvidia Container Tool Guide](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)
  * [Ollama Docker Image](https://ollama.ai/blog/ollama-is-now-available-as-an-official-docker-image)
  * [Docker Desktop for Windows](https://docs.docker.com/desktop/install/windows-install/)
    * [Docker Setup on Ubuntu 20.04](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04)
* Also worth looking into two repos:
  * [ollama_proxy_server](https://github.com/ParisNeo/ollama_proxy_server)
  * [ollama_docker_compose](https://github.com/tahercoolguy/ollama_docker_compose)

**Comment by kevinthedang** [comment]
For now, we will not worry about performance issues as it is mainly a hardware problem when it comes down to it. This will be a response time issue for when multiple users access the bot at the same time.
