### ISSUE TITLE
Secure Shutoff

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#8]
## Issue
* The bot is not exactly designed for many servers, but it is important to implement a shutoff sequence for servers that want to utilize the bot.

## Notes
* This will likely just be an environment variable and a command to shut it off 
  * However, it seems like a proxy bot will be needed for this if we want to do a shutoff and boot for the bot. Which is complexity that would not be nice to deal with or even a good idea in general.

**Comment by JT2M0L3Y** [comment]
An idea, use the local config.sjon to control an admin list for this (likely slash) command for shutting off the bot.
