### ISSUE TITLE
Application won't reply to user requests based on channel-toggle configuration

### ISSUE THREAD

**Issue by kevinthedang** [kevinthedang/discord-ollama#90]
## Issue
* When `channel-toggle` is set to true, conversations in Public and Private Threads will cease to work without reply.
* When `channel-toggle` is set to false, conversations in GuildText channels will cease to work without reply as well. 

## Steps to reproduce
* Configure the `channel-toggle` server preference to be true
* Open up a new public chat thread by running the Slash Command `/thread`
* Attempt to query the bot using @<bot_username> and it should not reply
* This also happens in GuildText channels when `channel-toggle` is set to false

## Solution(s)
* Implement a solution that will notify, based on the `channel-toggle`, that the bot cannot respond so users know to change the configuration.
* Another solution can be to do away with the toggle at all and allow the bot to chat anywhere as it poses no problem in general. If this course of action is taken, maintain how filename formats are created/edited as it makes the most sense for what is a channel chat history and what is a thread chat history.

## References
* Refer to `commands/channelToggle.ts` [here](https://github.com/kevinthedang/discord-ollama/blob/master/src/commands/channelToggle.ts) and `events/messageCreate.ts` [here ](https://github.com/kevinthedang/discord-ollama/blob/master/src/events/messageCreate.ts) for usage.

**Comment by kevinthedang** [comment]
I am in favor of the second solution as it will be 1 less configuration to worry about. 

If it becomes too complex, the first solution is a lot faster to implement

**Comment by JT2M0L3Y** [comment]
> I am in favor of the second solution as it will be 1 less configuration to worry about.
> 
> If it becomes too complex, the first solution is a lot faster to implement

I think this is the best course of action.

**Comment by kevinthedang** [comment]
Now realizing that if we just make it universal that `"<channel_id>-<username>.json"` universal then it makes sense no matter the context. 

* Private threads should only ever have 1 person as it is private.
* The [threadDelete](https://github.com/kevinthedang/discord-ollama/blob/master/src/events/threadDelete.ts) event will now have to handle possible multiple chat histories if for SOME reason multiple people talk in that channel.
* In a general channel, a user's history should still only be autonomous from other users.

This shouldn't be crazy but it makes sense. Have a universal chat history name but treat them by case on how they are Created, Read, Updated, Deleted (CRUD).

cc: @JT2M0L3Y

**Comment by kevinthedang** [comment]
Upon testing out `Private Threads` I have found this. Keep this commend below in mind when implementing a solution for this bug.

![image](https://github.com/user-attachments/assets/06e1c0ed-5651-4d1b-8adb-9817084a0ad0)
